language: ruby

addons:
  hosts:
    - local.durhamatletico.com

services:
  - docker

git:
  depth: 5

install:
  - sudo apt-get remove docker-engine
  - sudo apt-get -y install   apt-transport-https   ca-certificates   curl
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce=17.05.0~ce-0~ubuntu-trusty
  - docker --version
  - docker-compose pull
  - docker-compose run --rm php composer install -d tests --prefer-dist --no-interaction
  - cd themes/atletico; bundle install
  - cd ../..; tests/scripts/build.sh

script:
  - cd themes/atletico; bundle exec scss-lint
  - docker-compose exec -T --user 82 php tests/bin/behat -c tests/behat.yml --colors -vvv -f progress --strict --tags=~@failing
