language: ruby

services:
  - docker

git:
  depth: 5

install:
  - docker-compose pull
  - docker-compose up -d
  - docker-compose exec -T php composer install -d tests --prefer-dist --no-interaction
  - cd themes/atletico; bundle install
  - cd ../..; tests/scripts/build.sh

script:
  - cd themes/atletico; bundle exec scss-lint
  - docker exec durhamatletico_php tests/bin/behat --no-colors -c tests/behat.yml -f progress --tags=~@failing

