version: '2'
services:
  web:
    dns: 8.8.8.8
    image: durhamatletico/durhamatletico
    ports:
      - '8000:80'
    depends_on:
      - db
      - memcached
    volumes:
      - .:/var/www/html
  selenium:
    image: selenium/standalone-chrome-debug:2.53.0
    ports:
      - '4444:4444'
      - '5900:5900'
  cli:
    image: blinkreaction/drupal-cli:stable
    depends_on:
      - web
      - db
    volumes_from:
      - web:rw
  memcached:
    ports:
      - '11212:11211'
    image: memcached:1.4.25
  db:
    image: mysql:5.5.49
    ports:
      - '3308:3306'
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: 'durhamatletico_docker'
      MYSQL_ROOT_PASSWORD: 'root'
