version: '2'
services:
  web:
    dns: 8.8.8.8
    image: tbfisher/drupal-nginx:php-5.5.x
    ports:
      - '8000:80'
      - '4438:443'
    depends_on:
      - db
      - memcached
    volumes:
      - .:/var/www/web
  selenium:
    image: selenium/standalone-chrome-debug:2.53.0
  cli:
    image: blinkreaction/drupal-cli:stable
    depends_on:
      - web
      - db
    volumes_from:
      - web:rw
  memcached:
    image: memcached:1.4.25
  db:
    image: mysql:5.5.49
    volumes:
      - .mysql_data/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'durhamatletico_docker'
      MYSQL_ROOT_PASSWORD: 'root'
