version: '2'
services:
  php:
    container_name: durhamatletico_php
    image: durhamatletico/durhamatletico-php-fpm:0.1
    volumes:
      - .docker/php-fpm/settings.php:/conf/settings.php
    volumes_from:
      - web:rw
    depends_on:
      - web
  web:
    container_name: durhamatletico_httpd
    hostname: local.durhamatletico.com
    environment:
      - GH_TOKEN
      - IMGUR_API_KEY
    image: durhamatletico/durhamatletico-apache:0.1
    ports:
      - '443:443'
    depends_on:
      - db
    volumes:
      - .:/var/www/html
      - .docker/php-fpm/settings.php:/conf/settings.php
  db:
    container_name: durhamatletico_db
    image: mariadb:5.5.47
    ports:
      - '3336:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - .docker/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: 'durhamatletico_docker'
      MYSQL_ROOT_PASSWORD: 'root'
  blackfire:
    container_name: durhamatletico_blackfire
    image: blackfire/blackfire
    environment:
        - BLACKFIRE_SERVER_ID
        - BLACKFIRE_SERVER_TOKEN
        - BLACKFIRE_CLIENT_ID
        - BLACKFIRE_CLIENT_TOKEN
  selenium:
    container_name: durhamatletico_selenium
    image: selenium/standalone-chrome-debug:2.53.0
volumes:
  mysql-data:
    driver: local
