version: "2"
services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: durhamatletico_docker
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
     - mysql-data:/var/lib/mysql

  php:
    image: wodby/drupal-php:7.0-2.4.3
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: durhamatletico_docker
      DB_DRIVER: mysql
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting below
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - .:/var/www/html:cached
      - ./.docker/php-fpm/settings.php:/conf/settings.php

  nginx:
    image: wodby/drupal-nginx:8-1.13-2.4.2
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - .:/var/www/html:cached
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:local.durhamatletico.com'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.drupal.docker.localhost'

  terminus:
    image: savaslabs/terminus-docker
    environment:
      TERMINUS_CACHE_DIR: "/terminus/cache"
    volumes:
      - terminus-data:/terminus/cache
      - ./:/app:cached

  memcached:
   image: wodby/memcached:1.4-2.0.0

  portainer:
    image: portainer/portainer
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.drupal.docker.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=DEBUG --defaultEntryPoints='https' --entryPoints="Name:https Address::443 TLS:/certs/crt.txt,/certs/key.txt" --entryPoints="Name:http Address::80"
    ports:
      - '8000:80'
      - '80:80'
      - '443:443'
      - '8080:8080' # Dashboard
    volumes:
      - ./certs:/certs/
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mysql-data:
    driver: local
  terminus-data:
    driver: local
