resources:
  tournament_rest_resource:
    GET:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - cookie
link_domain: null
_core:
  default_config_hash: E9VXRiWZNet4YVBv8j9WQmTlgb-rOjo0MiCSdgV0Guw
