smtp_on: true
smtp_host: smtp.mailgun.org
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: info@durhamatletico.com
smtp_password: nottherealpassword
smtp_from: info@durhamatletico.com
smtp_fromname: 'Durham Atletico'
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
_core:
  default_config_hash: ZfbmfcSfeKOEssW5y01Z6rijotca6J_bKMFGQ1t0GD0
